In [1]:
# dependencies

from Bio import AlignIO
from Bio import SeqIO
import re
import pandas as pd
from ete3 import NCBITaxa

In [3]:
# results in FASTA form into dataframe

def pfam_results(results_input):
    data = {'accession': [], 'taxon': [], 'seq identifier': [], 'I Helix': []}
    with open(results_input) as fp:
        for record in SeqIO.parse(fp, "fasta"):
            seqident = re.findall(r"\|(?P<sequence_id>\w+)\|", record.id)
            accession = record.description
            taxon = re.findall(r"OX=(\d+)", record.description)
            sequence = str(record.seq)

            # attaching to dictionary
            data['seq identifier'].append(", ".join(seqident))
            data['accession'].append(accession)
            data['taxon'].append(", ".join(taxon))
            data['I Helix'].append(sequence)

    df = pd.DataFrame.from_dict(data)
    return df

In [4]:
# Converting HMM search output for pfam data to FASTA file
input = '/home/alecia/chapter3-repo/output/hmm_search_2/pfam/3/ihelixhits_e_0p001_z__T_.aln'
outfile_fasta = '/home/alecia/chapter3-repo/output/hmm_search_2/pfam/3/ihelixhits_e_0p001_z__T_.fasta'

with open(input) as infile:
    alignment = AlignIO.read(infile, 'stockholm')

SeqIO.write(alignment, outfile_fasta, 'fasta')

278757

In [5]:
pfam_r1 = pfam_results('/home/alecia/chapter3-repo/output/hmm_search_1/pfam/3/ihelixhits_e_0p001_z__T_.fasta')
pfam_r2 = pfam_results('/home/alecia/chapter3-repo/output/hmm_search_2/pfam/3/ihelixhits_e_0p001_z__T_.fasta')

In [6]:
pfam_r1

,accession,taxon,seq identifier,I Helix
0,tr|A0A498MRP4|A0A498MRP4_LABRO/720-751 [subseq...,84645,A0A498MRP4,-DGLVIACL-DV-I-EA--G---TET--T--A-T--TLR-WGLLFMIKY
1,tr|A0A498MRP4|A0A498MRP4_LABRO/1166-1197 [subs...,84645,A0A498MRP4,-EGLVISCL-DV-I-EA--G---TET--T--A-T--TLR-WGLLFMIKY
2,tr|A0A498MRP4|A0A498MRP4_LABRO/1618-1649 [subs...,84645,A0A498MRP4,-DGLVIICL-DV-I-EA--G---TET--T--T-T--TLR-WGLLFMIKY
3,tr|A0A498MRP4|A0A498MRP4_LABRO/2174-2205 [subs...,84645,A0A498MRP4,-DGLVISCL-DV-I-EA--G---TET--T--A-T--TLR-WGLLFMIKY
4,tr|A0A498MRP4|A0A498MRP4_LABRO/2626-2657 [subs...,84645,A0A498MRP4,-DGLVISCL-DV-I-EA--G---SET--T--A-T--TLR-WGLLFMIKY
...,...,...,...,...
162079,tr|A0A2S3GQM6|A0A2S3GQM6_9POAL/311-340 [subseq...,206008,A0A2S3GQM6,---LRDFCI-SF-V-LA--G---RDT--S--S-V--ALA-WFFWLLASH
162080,tr|A0A8X7P7K3|A0A8X7P7K3_BRACI/295-322 [subseq...,52824,A0A8X7P7K3,-----RECK-LF-Y-FA--G---QET--T--S-V--LLV-WTMILLSHH
162081,tr|A0A7S8A7J9|A0A7S8A7J9_9BRAD/226-256 [subseq...,1325114,A0A7S8A7J9,-DEMVSMVF-LL-L-AA--G---SET--T--T-H--LIS-GSAYELLR-
162082,tr|A0A395IRT2|A0A395IRT2_9HELO/207-235 [subseq...,38457,A0A395IRT2,---ILANMI-TF-L-IA--G---HET--I--S-G--ILS-FVFLNLMK-
162083,tr|A0A6P8J172|A0A6P8J172_ACTTE/293-314 [subseq...,6105,A0A6P8J172,----------TL-F-LA--G---SET--T--S-T--TLS-WAVVYLL--

In [7]:
pfam_r2

,accession,taxon,seq identifier,I Helix
0,tr|A0A182XW67|A0A182XW67_ANOST/287-321 [subseq...,30069,A0A182XW67,LDMTQV--AGQCY-S-F-F-I--A----G------FE--T-SAS--...
1,tr|A0A182XW67|A0A182XW67_ANOST/819-853 [subseq...,30069,A0A182XW67,MTLNEL--AAQVF-I-F-F-L--A----G------FE--T-SST--...
2,tr|A0A182XW67|A0A182XW67_ANOST/1316-1351 [subs...,30069,A0A182XW67,LTMNEL--AAQVF-I-F-F-V--A----G------FE--T-SST--...
3,tr|A0A182XW67|A0A182XW67_ANOST/1825-1860 [subs...,30069,A0A182XW67,LTLNEL--AAQVF-V-F-F-L--A----G------FE--T-SST--...
4,tr|A0A182XW67|A0A182XW67_ANOST/2334-2369 [subs...,30069,A0A182XW67,LTHNEL--AAQVL-I-F-F-L--A----G------FE--T-SST--...
...,...,...,...,...
278752,tr|A0A1Y2UC39|A0A1Y2UC39_9PEZI/289-316 [subseq...,1001938,A0A1Y2UC39,---------MEAI-L-F-T-V--A----G------GD--T-TST--...
278753,tr|A0A1H4E4S6|A0A1H4E4S6_9BURK/238-270 [subseq...,83784,A0A1H4E4S6,LSEVEL--LQNCI-F-I-L-N--A----G------HE--T-TTN--...
278754,tr|A0A0E4FSG9|A0A0E4FSG9_9BRAD/239-274 [subseq...,1355477,A0A0E4FSG9,LSDAEL--ISMLW-G-M-L-L--G----G------FV--T-TAA--...
278755,tr|A0A210Q976|A0A210Q976_MIZYE/289-323 [subseq...,6573,A0A210Q976,FTDNNL--TTLIG-N-V-F-S--A----G------TE--T-TAT--...
278756,tr|A0A9W6F151|A0A9W6F151_9CHLO/321-353 [subseq...,330485,A0A9W6F151,---RKI--AETVM-D-F-L-F--A----S------QD--A-STA--...

In [8]:
r1r2_merged_pfam = (pd.merge(pfam_r1, pfam_r2, how='outer', on=['seq identifier', 'taxon'])
                    .fillna(0)
                    .drop_duplicates(subset=['seq identifier']))
r1r2_merged_pfam

,accession_x,taxon,seq identifier,I Helix_x,accession_y,I Helix_y
0,tr|A0A498MRP4|A0A498MRP4_LABRO/720-751 [subseq...,84645,A0A498MRP4,-DGLVIACL-DV-I-EA--G---TET--T--A-T--TLR-WGLLFMIKY,tr|A0A498MRP4|A0A498MRP4_LABRO/1164-1198 [subs...,-NMEGL--VISCL-D-V-I-E--A----G------TE--T-TAT--...
21,tr|A0A182Y3M0|A0A182Y3M0_ANOST/316-347 [subseq...,30069,A0A182Y3M0,-EEIAAQAF-VF-F-FG--G---FET--S--T-T--TLT-CALHLLAKY,tr|A0A182Y3M0|A0A182Y3M0_ANOST/313-348 [subseq...,LTFEEI--AAQAF-V-F-F-F--G----G------FE--T-STT--...
85,tr|A0A9Q0JPW7|A0A9Q0JPW7_9ROSI/567-595 [subseq...,218843,A0A9Q0JPW7,-RYLRDIIL-NI-M-FA--G---KDT--S--A-N--TIS-WFFYML---,tr|A0A9Q0JPW7|A0A9Q0JPW7_9ROSI/564-599 [subseq...,MNDRYL--RDIIL-N-I-M-F--A----G------KD--T-SAN--...
109,tr|A0A8J4WTT4|A0A8J4WTT4_CLAMG/475-505 [subseq...,1594786,A0A8J4WTT4,--DVYGSVA-EL-L-LA--G---VDT--T--S-I--TLM-WALYLLSQN,tr|A0A8J4WTT4|A0A8J4WTT4_CLAMG/471-506 [subseq...,MSKKDV--YGSVA-E-L-L-L--A----G------VD--T-TSI--...
145,tr|A0A553R2M7|A0A553R2M7_9TELE/301-332 [subseq...,623744,A0A553R2M7,-ENLMMTVM-NL-F-VA--G---TDT--T--G-T--TLR-WGLMLMAKY,tr|A0A553R2M7|A0A553R2M7_9TELE/300-333 [subseq...,--DENL--MMTVM-N-L-F-V--A----G------TD--T-TGT--...
...,...,...,...,...,...,...
294301,0,100035,A0A7C8I5D7,0,tr|A0A7C8I5D7|A0A7C8I5D7_9PLEO/294-325 [subseq...,----VL--RDQIV-Q-A-M-M--A----S------TE--T-TGS--...
294302,0,50452,A0A087GH04,0,tr|A0A087GH04|A0A087GH04_ARAAL/284-319 [subseq...,FTHENV--KSMIL-D-I-V-V--P----G------TD--T-AAA--...
294303,0,1001938,A0A1Y2UC39,0,tr|A0A1Y2UC39|A0A1Y2UC39_9PEZI/289-316 [subseq...,---------MEAI-L-F-T-V--A----G------GD--T-TST--...
294304,0,1355477,A0A0E4FSG9,0,tr|A0A0E4FSG9|A0A0E4FSG9_9BRAD/239-274 [subseq...,LSDAEL--ISMLW-G-M-L-L--G----G------FV--T-TAA--...
294305,0,330485,A0A9W6F151,0,tr|A0A9W6F151|A0A9W6F151_9CHLO/321-353 [subseq...,---RKI--AETVM-D-F-L-F--A----S------QD--A-STA--...

In [9]:
ncbi = NCBITaxa()

In [11]:
# Function to fetch lineage and ranks using NCBITaxa
def get_lineage_and_ranks(taxon_id):
    try:
        lineage = ncbi.get_lineage(taxon_id)  # List of lineage taxids
        ranks = ncbi.get_rank(lineage)  # Get ranks for the lineage
        
        # Map the taxid to its corresponding name and rank
        lineage_and_ranks = {ncbi.get_taxid_translator([taxid])[taxid]: ranks[taxid] 
                             for taxid in lineage if taxid in ranks}
        
        return lineage_and_ranks
    except:
        return None  # Return None if the ID is not found or there is an error

In [12]:
# Apply ncbi taxa to dataframe in chunks to access lineage and ranks

r1r2_merged_pfam["lineage_and_ranks"] = r1r2_merged_pfam["taxon"].apply(lambda x: get_lineage_and_ranks(int(x)) if pd.notna(x) else None)

/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 299123 was translated into 40157
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 59451 was translated into 3371016
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 322609 was translated into 85044
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2052317 was translated into 3107663
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 914237 was translated into 2792576
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2133754 was translated into 78057
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 1276135 was translated into 3151832
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 139420 was translated into 2498619
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 237656 was translated into 33907
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 369932 was translated into 369930
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2735433 was translated into 3014751
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 1081105 was translated into 1649241
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 182895 was translated into 3235156
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2508778 was translated into 209559
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 187437 was translated into 3150915
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 707209 was translated into 83224
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 1504303 was translated into 72036
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 85948 was translated into 147567
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 237631 was translated into 5270
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 129465 was translated into 3147026
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 305698 was translated into 376165
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 262131 was translated into 2953425
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 686832 was translated into 76867
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 1240228 was translated into 8855
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 436010 was translated into 1759441
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 694573 was translated into 105487
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 553056 was translated into 3097545
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 1660074 was translated into 1660076
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 90246 was translated into 3371109
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 658882 was translated into 2773310
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 503106 was translated into 2795749
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2750085 was translated into 2750084
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 1827387 was translated into 1951219
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 40710 was translated into 1967468
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 114529 was translated into 2246
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2792677 was translated into 48254
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2067667 was translated into 2304603
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 311220 was translated into 3241090
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 1064592 was translated into 27288
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 137245 was translated into 3399148
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 1224075 was translated into 2203200
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 237610 was translated into 47885
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 227732 was translated into 143450
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/home/alecia/anaconda3/envs/taxon/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 1211136 was translated into 395568
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))

In [13]:
r1r2_merged_pfam

,accession_x,taxon,seq identifier,I Helix_x,accession_y,I Helix_y,lineage_and_ranks
0,tr|A0A498MRP4|A0A498MRP4_LABRO/720-751 [subseq...,84645,A0A498MRP4,-DGLVIACL-DV-I-EA--G---TET--T--A-T--TLR-WGLLFMIKY,tr|A0A498MRP4|A0A498MRP4_LABRO/1164-1198 [subs...,-NMEGL--VISCL-D-V-I-E--A----G------TE--T-TAT--...,"{'root': 'no rank', 'cellular organisms': 'no ..."
21,tr|A0A182Y3M0|A0A182Y3M0_ANOST/316-347 [subseq...,30069,A0A182Y3M0,-EEIAAQAF-VF-F-FG--G---FET--S--T-T--TLT-CALHLLAKY,tr|A0A182Y3M0|A0A182Y3M0_ANOST/313-348 [subseq...,LTFEEI--AAQAF-V-F-F-F--G----G------FE--T-STT--...,"{'root': 'no rank', 'cellular organisms': 'no ..."
85,tr|A0A9Q0JPW7|A0A9Q0JPW7_9ROSI/567-595 [subseq...,218843,A0A9Q0JPW7,-RYLRDIIL-NI-M-FA--G---KDT--S--A-N--TIS-WFFYML---,tr|A0A9Q0JPW7|A0A9Q0JPW7_9ROSI/564-599 [subseq...,MNDRYL--RDIIL-N-I-M-F--A----G------KD--T-SAN--...,"{'root': 'no rank', 'cellular organisms': 'no ..."
109,tr|A0A8J4WTT4|A0A8J4WTT4_CLAMG/475-505 [subseq...,1594786,A0A8J4WTT4,--DVYGSVA-EL-L-LA--G---VDT--T--S-I--TLM-WALYLLSQN,tr|A0A8J4WTT4|A0A8J4WTT4_CLAMG/471-506 [subseq...,MSKKDV--YGSVA-E-L-L-L--A----G------VD--T-TSI--...,"{'root': 'no rank', 'cellular organisms': 'no ..."
145,tr|A0A553R2M7|A0A553R2M7_9TELE/301-332 [subseq...,623744,A0A553R2M7,-ENLMMTVM-NL-F-VA--G---TDT--T--G-T--TLR-WGLMLMAKY,tr|A0A553R2M7|A0A553R2M7_9TELE/300-333 [subseq...,--DENL--MMTVM-N-L-F-V--A----G------TD--T-TGT--...,"{'root': 'no rank', 'cellular organisms': 'no ..."
...,...,...,...,...,...,...,...
294301,0,100035,A0A7C8I5D7,0,tr|A0A7C8I5D7|A0A7C8I5D7_9PLEO/294-325 [subseq...,----VL--RDQIV-Q-A-M-M--A----S------TE--T-TGS--...,"{'root': 'no rank', 'cellular organisms': 'no ..."
294302,0,50452,A0A087GH04,0,tr|A0A087GH04|A0A087GH04_ARAAL/284-319 [subseq...,FTHENV--KSMIL-D-I-V-V--P----G------TD--T-AAA--...,"{'root': 'no rank', 'cellular organisms': 'no ..."
294303,0,1001938,A0A1Y2UC39,0,tr|A0A1Y2UC39|A0A1Y2UC39_9PEZI/289-316 [subseq...,---------MEAI-L-F-T-V--A----G------GD--T-TST--...,"{'root': 'no rank', 'cellular organisms': 'no ..."
294304,0,1355477,A0A0E4FSG9,0,tr|A0A0E4FSG9|A0A0E4FSG9_9BRAD/239-274 [subseq...,LSDAEL--ISMLW-G-M-L-L--G----G------FV--T-TAA--...,"{'root': 'no rank', 'cellular organisms': 'no ..."
294305,0,330485,A0A9W6F151,0,tr|A0A9W6F151|A0A9W6F151_9CHLO/321-353 [subseq...,---RKI--AETVM-D-F-L-F--A----S------QD--A-STA--...,"{'root': 'no rank', 'cellular organisms': 'no ..."

In [ ]:
keys_ranks = ['superkingdom', 'kingdom', 'phylum']